### ISSUE TITLE
Replace xrange for Python 3.x compatibility

### ISSUE THREAD

**Issue by mario56865** [QTIM-Lab/DeepNeuro#24]
I can't use Deepneuro on my Python 3.6 installation because of xrange

> Traceback (most recent call last):
  File "main.py", line 143, in <module>
    main()
  File "main.py", line 101, in main
    output_type='categorical_label', num_outputs=config["n_labels"], batch_norm=True)
  File "/home/eashver/anaconda3/envs/python_tf/lib/python3.6/site-packages/deepneuro-0.1.1-py3.6.egg/deepneuro/models/model.py", line 98, in __init__
    self.build_model()
  File "/home/eashver/anaconda3/envs/python_tf/lib/python3.6/site-packages/deepneuro-0.1.1-py3.6.egg/deepneuro/models/unet.py", line 52, in build_model
    for level in xrange(self.depth):
NameError: name 'xrange' is not defined

Maybe we could replace with range for compatibility with python 3

**Comment by AndrewBeers** [comment]
Hello! I've run Python 2to3 (check it out here -- https://docs.python.org/2/library/2to3.html) on all of DeepNeuro. This should replace xrange with range, and also fix all of the other Python 2-isms that I've built into the code. Check out the branch and give it a shot (checkout instructions here: https://gist.github.com/markSci5/5916003), and thanks for letting me know!

**Comment by mario56865** [comment]
Thank You So much!

**Comment by jmbrown89** [comment]
Nice one Beers!
