### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by ujjwalbaid0408** [QTIM-Lab/DeepNeuro#43]
I have run the docker but stuck at following error

nvidia-docker run --rm -v /home/user/Desktop/data/mets:/INPUT_DATA qtimlab/deepneuro_segment_mets segment_mets pipeline -T1 /INPUT_DATA/T1pre -T1POST /INPUT_DATA/T1post -FLAIR /INPUT_DATA/FLAIR -T2 /INPUT_DATA/T2 -output_folder /INPUT_DATA/op

Using TensorFlow backend.
File loading completed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 231, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/segment_mets", line 11, in <module>
    load_entry_point('deepneuro', 'console_scripts', 'segment_mets')()
  File "/home/DeepNeuro/deepneuro/pipelines/Segment_Brain_Mets/cli.py", line 96, in main
    Segment_Mets_cli()
  File "/home/DeepNeuro/deepneuro/pipelines/Segment_Brain_Mets/cli.py", line 33, in __init__
    getattr(self, args.command)()
  File "/home/DeepNeuro/deepneuro/pipelines/Segment_Brain_Mets/cli.py", line 86, in pipeline
    predict_brain_mets(args.output_folder, T2=args.T2, T1POST=args.T1POST, T1PRE=args.T1, FLAIR=args.FLAIR, ground_truth=None, input_directory=args.input_directory, bias_corrected=args.debiased, resampled=args.resampled, registered=args.registered, skullstripped=args.skullstripped, preprocessed=args.preprocessed, save_preprocess=args.save_preprocess, save_all_steps=args.save_all_steps, output_segmentation_filename=args.segmentation_output)
  File "/home/DeepNeuro/deepneuro/pipelines/Segment_Brain_Mets/predict.py", line 34, in predict_brain_mets
    mets_model = load_model_with_output(model_name='mets_enhancing', outputs=[ModelPatchesInference(**mets_prediction_parameters)], postprocessors=[BinarizeLabel(postprocessor_string='_label')], wcc_weights={0: 0.1, 1: 3.0})
  File "/home/DeepNeuro/deepneuro/pipelines/shared.py", line 50, in load_model_with_output
    model = load_old_model(load(model_name), **kwargs)
  File "/home/DeepNeuro/deepneuro/models/model.py", line 257, in load_old_model
    model = KerasModel(model=load_model(model_file, custom_objects=custom_objects))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1017, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1003, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 730, in from_config
    function = func_load(config['function'], globs=globs)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 235, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

**Comment by AndrewBeers** [comment]
Hi,

I apologize for this problem -- it was the result of hastily updating a model without re-running our Docker tests. For future reference, this error was caused by a model that was created in Keras with Python 2, but is run inside the Docker using Python 3. I have converted the model to Python 3, and modified the Docker to pull this new model. To use it, you must re-pull this Docker container using the following command:

`docker pull qtimlab/deepneuro_segment_mets:latest`

Please post here if you hit another error with this module.

Best,
Andrew
