### ISSUE TITLE
KeyError: running glioblastoma segmentation from command line

### ISSUE THREAD

**Issue by agatakrason** [QTIM-Lab/DeepNeuro#50]
I am getting an error  when I am runnign glioblastoma segmentation via cmd. 

This is my cmd: 
`segment_gbm pipeline -T1 T1 -T1POST T1POST -FLAIR FLAIR -output_folder output  -wholetumor_output wholetumor. nii.gz -enhancing_output enhancing.nii.gz`

I got an key error :

```
 ('Starting New Case...',)
('Whole Tumor Prediction',)
('======================',)
('Working on image.. ', 'output')
Traceback (most recent call last):
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\Scripts\segment_gbm-script.py", line 11, in <module>
    load_entry_point('deepneuro==0.2.3', 'console_scripts', 'segment_gbm')()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\cli.py", line 86, in main
    Segment_GBM_cli()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\shared.py", line 22, in __init__
    self.load()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\cli.py", line 16, in load
    super(Segment_GBM_cli, self).load()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\shared.py", line 48, in load
    getattr(self, args.command)()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\cli.py", line 82, in pipeline
    quiet=args.quiet)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\predict.py", line 123, in predict_GBM
    wholetumor_file = wholetumor_model.generate_outputs(data_collection, output_folder)[0]['filenames'][-1]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\models\model.py", line 163, in generate_outputs
    return_outputs += [output.generate()]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 131, in generate
    return self.generate_individual_case(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 153, in generate_individual_case
    input_data = self.data_collection.get_data(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 376, in get_data
    self.load_case_data(case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 317, in load_case_data
    data_group.preprocessed_case = copy.copy(data_group.data[self.current_case])
KeyError: 'output'

```
I don't know really what I am doing wrong.  
Could you help me please ?
I would be appreciate for any help please.

**Comment by agatakrason** [comment]
Right now, when I run the script with nii.gz inputs.
I got the following errors: 

Here code looks like this:
```
output_folder = "C:\\Users\\krasona\\PycharmProjects\\GlioblastomaSegmentation\\output"

if os.path.exists(output_folder):
    print("Output folder exists")
else:
    os.mkdir(output_folder)

T1PRE = "T1.nii.gz"
FLAIR = "FLAIR.nii.gz"
T1POST = "T1POST.nii.gz"
output_wholetumor_filename = "output_whole_tumor.nii.gz"
output_enhancing_filename = "enhancing_segmentation.nii.gz"


predict_GBM(output_folder,
                T1POST,
                FLAIR,
                T1PRE,
                bias_corrected=False,
                resampled=False,
                registered=False,
                skullstripped=False,
                preprocessed=False,
                save_only_segmentations=False,
                save_all_steps=True,
                output_wholetumor_filename = output_wholetumor_filename,
                output_enhancing_filename = output_wholetumor_filename,
                quiet=False)

```

Output errors:
```
'Starting New Case...',)
('Whole Tumor Prediction',)
('======================',)
('Working on image.. ', 'C:\\Users\\krasona\\PycharmProjects\\GlioblastomaSegmentation\\output')
('Working on Preprocessor:', 'Conversion')
('Working on Preprocessor:', 'N4BiasCorrection')
('Working on Preprocessor:', 'Registration')
('Working on Preprocessor:', 'ZeroMeanNormalization')
Traceback (most recent call last):
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\nibabel\loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\krasona\\PycharmProjects\\GlioblastomaSegmentation\\output\\FLAIR_N4Bias.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/krasona/PycharmProjects/GlioblastomaSegmentation/GlioblastomaSegmentationMain.py", line 51, in <module>
    quiet=False)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\predict.py", line 123, in predict_GBM
    wholetumor_file = wholetumor_model.generate_outputs(data_collection, output_folder)[0]['filenames'][-1]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\models\model.py", line 163, in generate_outputs
    return_outputs += [output.generate()]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 131, in generate
    return self.generate_individual_case(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 153, in generate_individual_case
    input_data = self.data_collection.get_data(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 376, in get_data
    self.load_case_data(case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 321, in load_case_data
    self.preprocess()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 304, in preprocess
    preprocessor.execute(self, return_array=False)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\preprocessing\preprocessor.py", line 73, in execute
    data_group.preprocessed_case, data_group.preprocessed_affine = data_group.get_data(return_affine=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_group.py", line 87, in get_data
    preprocessed_case, preprocessed_affine = read_image_files(self.preprocessed_case, return_affine=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 44, in read_image_files
    data, _, affine, data_format = convert_input_2_numpy(data_file, return_all=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 495, in convert_input_2_numpy
    return NUMPY_CONVERTER_LIST[input_format](input_data, return_all=True) + (input_format,)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 329, in nifti_2_numpy
    nifti = nib.load(input_filepath)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\nibabel\loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: 'C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\output\FLAIR_N4Bias.nii.gz'

Process finished with exit code 1

```

**Comment by JonathanChiang** [comment]
Hi Agata,

I'll be helping with this issue and try to reproduce on my end.

**Comment by abenpy** [comment]
if you replace output with the full directory path in '-output_folder output', e.g 'output' > ' /gpfs/scratch/bz957/brats/pipeline/testcase/output', it solved this problem.

**Comment by agatakrason** [comment]
But I am still getting this error:

```
('Starting New Case...',)
('Whole Tumor Prediction',)
('======================',)
('Working on image.. ', 'C:\\Users\\krasona\\PycharmProjects\\GlioblastomaSegmentation\\output')
('Working on Preprocessor:', 'Conversion')
('Working on Preprocessor:', 'N4BiasCorrection')
('Working on Preprocessor:', 'Registration')
('Working on Preprocessor:', 'ZeroMeanNormalization')
Traceback (most recent call last):
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\nibabel\loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\krasona\\PycharmProjects\\GlioblastomaSegmentation\\output\\FLAIR_N4Bias.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\Scripts\segment_gbm-script.py", line 11, in <module>
    load_entry_point('deepneuro==0.2.3', 'console_scripts', 'segment_gbm')()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\cli.py", line 86, in main
    Segment_GBM_cli()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\shared.py", line 22, in __init__
    self.load()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\cli.py", line 16, in load
    super(Segment_GBM_cli, self).load()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\shared.py", line 48, in load
    getattr(self, args.command)()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\cli.py", line 82, in pipeline
    quiet=args.quiet)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\predict.py", line 123, in predict_GBM
    wholetumor_file = wholetumor_model.generate_outputs(data_collection, output_folder)[0]['filenames'][-1]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\models\model.py", line 163, in generate_outputs
    return_outputs += [output.generate()]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 131, in generate
    return self.generate_individual_case(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 153, in generate_individual_case
    input_data = self.data_collection.get_data(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 376, in get_data
    self.load_case_data(case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 321, in load_case_data
    self.preprocess()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 304, in preprocess
    preprocessor.execute(self, return_array=False)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\preprocessing\preprocessor.py", line 73, in execute
    data_group.preprocessed_case, data_group.preprocessed_affine = data_group.get_data(return_affine=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_group.py", line 87, in get_data
    preprocessed_case, preprocessed_affine = read_image_files(self.preprocessed_case, return_affine=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 44, in read_image_files
    data, _, affine, data_format = convert_input_2_numpy(data_file, return_all=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 495, in convert_input_2_numpy
    return NUMPY_CONVERTER_LIST[input_format](input_data, return_all=True) + (input_format,)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 329, in nifti_2_numpy
    nifti = nib.load(input_filepath)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\nibabel\loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: 'C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\output\FLAIR_N4Bias.nii.gz'
```
