### ISSUE TITLE
FileNotFoundError: No such file or no access 

### ISSUE THREAD

**Issue by agatakrason** [QTIM-Lab/DeepNeuro#52]
Hi Guys,

I am having a problem when I am trying to run segment_GBM.
It stop because  it can not find a FLAIR_N4Bias.nii.gz file.  It created in output folder another files. 
T1_convert, T1POST_Convert and ect ... 
I dont know why there is an issue with \FLAIR_N4Bias.nii.gz

```
('Starting New Case...',)
('Whole Tumor Prediction',)
('======================',)
('Working on image.. ', 'C:\\Users\\krasona\\PycharmProjects\\GlioblastomaSegmentation\\output')
('Working on Preprocessor:', 'Conversion')
('Working on Preprocessor:', 'N4BiasCorrection')
('Working on Preprocessor:', 'Registration')
('Working on Preprocessor:', 'ZeroMeanNormalization')
Traceback (most recent call last):
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\nibabel\loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\krasona\\PycharmProjects\\GlioblastomaSegmentation\\output\\FLAIR_N4Bias.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/krasona/PycharmProjects/GlioblastomaSegmentation/GlioblastomaSegmentationMain.py", line 49, in <module>
    quiet=False)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\pipelines\Segment_GBM\predict.py", line 123, in predict_GBM
    wholetumor_file = wholetumor_model.generate_outputs(data_collection, output_folder)[0]['filenames'][-1]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\models\model.py", line 163, in generate_outputs
    return_outputs += [output.generate()]
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 131, in generate
    return self.generate_individual_case(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\output.py", line 153, in generate_individual_case
    input_data = self.data_collection.get_data(self.case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 376, in get_data
    self.load_case_data(case)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 321, in load_case_data
    self.preprocess()
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_collection.py", line 304, in preprocess
    preprocessor.execute(self, return_array=False)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\preprocessing\preprocessor.py", line 73, in execute
    data_group.preprocessed_case, data_group.preprocessed_affine = data_group.get_data(return_affine=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\data\data_group.py", line 87, in get_data
    preprocessed_case, preprocessed_affine = read_image_files(self.preprocessed_case, return_affine=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 44, in read_image_files
    data, _, affine, data_format = convert_input_2_numpy(data_file, return_all=True)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 495, in convert_input_2_numpy
    return NUMPY_CONVERTER_LIST[input_format](input_data, return_all=True) + (input_format,)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\utilities\conversion.py", line 329, in nifti_2_numpy
    nifti = nib.load(input_filepath)
  File "C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\nibabel\loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: 'C:\Users\krasona\PycharmProjects\GlioblastomaSegmentation\output\FLAIR_N4Bias.nii.gz'

Process finished with exit code 1
```

I would be appreciate for any help please.

**Comment by agatakrason** [comment]
![screenshots](https://user-images.githubusercontent.com/467863/64715255-697b2c00-d4c0-11e9-8b30-4a8b1d59f841.png)
It creates T1, T1POST and FLAIR_convert.nii.gz but it didn't create FLAIR_N4Bias.nii.gz

**Comment by abenpy** [comment]
Hi, 
I met the same problem, solved by install 3D Slicer. It will produce FLAIR_N4Bias.nii.gz, and also the coregister and skull_striped nifty files for the next preprocessing steps.

Or you can do the debias, coregister and skull_striped through other tools, and just input 'segment_gbm pipeline -T1 <file> -T1POST <file> -FLAIR <file> -output_folder <directory> -wholetumor_output <string> -enhancing_output <string> -debiased -registered -skullstripped -preprocessed  -save_all_steps ' in the command line

Btw, It is better to install Deepneuro through Docker because it will install the supported packages for Deepneuro.
Best,

**Comment by agatakrason** [comment]
Hello,
Yeah, thanks a lot @abenpy ! Now it is running.

Thanks for your help. 

Best regards,

**Comment by agatakrason** [comment]
Hello,

Thanks a lot for your email reply.
It help me a lot.
I have one more question. Right now I  go ahead and  I got new error
 PycharmProjects\GlioblastomaSegmentation\venv\lib\site-packages\deepneuro\outputs\segmentation.py",
line 245, in grab_patch
    output_patches[corner_idx, ...] = input_data[tuple(output_slice)]
ValueError: could not broadcast input array from shape (64,64,8,2) into
shape (64,64,8,3)

Btw, maybe did you get the sameg issue ?

Best regards,
Agata

śr., 18 wrz 2019 o 00:06 abenpy <notifications@github.com> napisał(a):

**Comment by abenpy** [comment]
Hi, I guess there is a bug in there code.  change the following in the 'predict.py':'    wholetumor_prediction_parameters = {'output_directory': output_folder,
                        'output_filename': output_wholetumor_filename,
                        'batch_size': 50,
                        'patch_overlaps': 6,
                        'output_patch_shape': (56, 56, 6, 1),
                        # 'input_channels': [0, 1],
                        'input_channels': [0, 1, 2],
                        'case_in_filename': False,
                        'verbose': verbose}
'
input_channels from [0,1] to [0,1,2]

Then it will work
